/*   Generated by AspectJ version 0.7beta7 */
import Hello;
import ResourceAccounting;
public class Hello extends java.lang.Object  {              //from Hello.java:3
  static java.lang.Object o1 = new java.lang.Object();      //from Hello.java:4
  static  {                                                 //from Hello.java:5
    java.lang.System.out.println("o1 = " + Hello.o1);       //from Hello.java:6
    java.lang.Object o2 = Hello.new$call1();                //from Hello.java:7
    java.lang.System.out.println("o2 = " + o2);             //from Hello.java:8
  }

  java.lang.Object o3 = new java.lang.Object();             //from Hello.java:10
  {                                                         //from Hello.java:11
    java.lang.System.out.println("o3 = " + o3);             //from Hello.java:12
    java.lang.Object o4 = new$call3();                      //from Hello.java:13
    java.lang.System.out.println("o4 = " + o4);             //from Hello.java:14
  }

  Hello()  {                                                //from Hello.java:16
    java.lang.Object o5 = new$call5();                      //from Hello.java:17
    java.lang.System.out.println("o5 = " + o5);             //from Hello.java:18
  }

  public static void main(java.lang.String[] args)  {       //from Hello.java:20
    Hello h = new Hello();                                  //from Hello.java:21
    java.lang.System.out.println("h = " + h);               //from Hello.java:22
  }

  static java.lang.Object new$call1()  {                    //from Hello.java:7
    ((ResourceAccounting)((ResourceAccounting)null).aspectOf()).before$ajc0(null);
    java.lang.Object thisResult = null;                     //from Hello.java:7
    thisResult = Hello.new$call1$Hello$static$call0();
    return thisResult;
  }

  public static final java.lang.Object new$call1$Hello$static$call0()  {  //from Hello.java:7
    return new java.lang.Object();
  }

  java.lang.Object new$call3()  {                           //from Hello.java:13
    ((ResourceAccounting)((ResourceAccounting)null).aspectOf()).before$ajc0(null);
    java.lang.Object thisResult = null;                     //from Hello.java:13
    thisResult = ((Hello)this).new$call3$Hello$call2();
    return thisResult;
  }

  public final java.lang.Object new$call3$Hello$call2()  {  //from Hello.java:13
    return new java.lang.Object();
  }

  java.lang.Object new$call5()  {                           //from Hello.java:17
    ((ResourceAccounting)((ResourceAccounting)null).aspectOf()).before$ajc0(null);
    java.lang.Object thisResult = null;                     //from Hello.java:17
    thisResult = ((Hello)this).new$call5$Hello$call4();
    return thisResult;
  }

  public final java.lang.Object new$call5$Hello$call4()  {  //from Hello.java:17
    return new java.lang.Object();
  }

}
