/*   Generated by AspectJ version 0.7beta7 */
import ResourceAccounting;
public class ResourceAccounting extends java.lang.Object  {  //from ResourceAccounting.java:1
  public ResourceAccounting()  {
    super();
  }

  private static final ResourceAccounting aspect$ = new ResourceAccounting();
  public static java.lang.Object aspectOf()  {
    return aspect$;
  }

  public static boolean hasAspect()  {
    return aspect$ != null;
  }

  public final void before$ajc0(org.aspectj.runtime.JoinPoint thisJoinPoint)  {  //from ResourceAccounting.java:2
    java.lang.System.out.println("Constructing...");        //from ResourceAccounting.java:3
  }

}
