/signature [
(                    http://www.ccs.neu.edu/home/dougo )
] def

(compilation by Doug Orleans:) (NorCal '94)
(recorded sometime in 1994 from CDs)

[()
 ()
 [(Steel Pole Bath Tub) (Pseudoephedrine Hydrochloride 5:26)]
 [(Thinking Fellers Union Local 282) ()]
 [() (Hummingbird in a Cube of Ice 4:05)]
 [(Pavement) (Heckler Spray 1:07 / From Now On 2:04)]
 [(The Meices) (That Good One 2:27)]
 [(Overwhelming Colorfast) (Toss Up 1:40)]
 [(Green Day) (2,000 Light Years Away 2:25)]
 [(Barbara Manning) (Straw Man 2:16)]
 [(Tiger Trap) (Words and Smiles 2:18)]
 [(Little My) (Misdemeanor 3:03)]
 [(Fibulator) (Her Hair All One Thing 4:37)]
 [(Star Pimp) (Greatest Hits of Love 2:33)]
 [(Tilt) (Dead Bum 2:34)]
 [(Jawbreaker) (Bivouac 10:07)]
 ]
[()
 ()
 [(Victim's Family) (Supermarket Nightmare 2:51)]
 [(J Church) (Why I Liked Bikini Kill 1:42)]
 [(Samiam) (Hey Brother 3:23)]
 [(Neurosis) (Enemy of the Sun 7:34)]
 [(Overwhelming Colorfast) (Ira Schrader 1:51)]
 [(Tiger Trap) (Don't Ask 2:00)]
 [(The San Francisco Seals) (Day 12 2:34)]
 [(Pavement) (Unfair 2:33)]
 [(Pot Valiant) (Nugget Killer 3:26)]
 [(The Meices) (That Other Good One 6:43)]
 [(Thinking Fellers Union Local 282) (Father 5:25)]
 [(Sausage) (Caution Should Be Used While Driving a)]
 [() (Motor Vehicle or Operating Machinery 6:22)]
 ]
double-album



