#lang planet dyoo/whalesong

(require (planet dyoo/whalesong/web-world))

(xexp?
 '(div (@ (class "board"))
       (div
        (span (@ (class "border")) "8")
        (span (@ (class "white white-square cursor")) "\u265B")
        (a ((class "black black-square")) "\u265C")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "white black-square")) "\u265F")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "white black-square")) "\u265C")
        (span (@ (class "white white-square")) "\u265C")
        (a ((class "black black-square")) "\u265B"))
       (div
        (span (@ (class "border")) "7")
        (span (@ (class "white black-square")) "\u265F")
        (a ((class "black white-square")) "\u265D")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "black white-square")) "\u265E")
        (span (@ (class "black black-square")) "\u265D")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "black black-square")) "\u265D")
        (span (@ (class "blank white-square")) "&nbsp;"))
       (div
        (span (@ (class "border")) "6")
        (a ((class "black white-square")) "\u265E")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "white white-square")) "\u265C")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "black black-square")) "\u265E"))
       (div
        (span (@ (class "border")) "5")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "white black-square")) "\u265E")
        (a ((class "black white-square")) "\u265F")
        (span (@ (class "white black-square")) "\u265E")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "white black-square")) "\u265E")
        (span (@ (class "white white-square")) "\u265D"))
       (div
        (span (@ (class "border")) "4")
        (span (@ (class "white white-square")) "\u265C")
        (span (@ (class "white black-square")) "\u265C")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "black black-square")) "\u265E")
        (a ((class "black white-square")) "\u265C")
        (span (@ (class "black black-square")) "\u265E")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "black black-square")) "\u265E"))
       (div
        (span (@ (class "border")) "3")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "white black-square")) "\u265E")
        (span (@ (class "white white-square")) "\u265D")
        (span (@ (class "blank black-square")) "&nbsp;")
        (a ((class "black white-square")) "\u265C")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "black white-square")) "\u265F"))
       (div
        (span (@ (class "border")) "2")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "white black-square")) "\u265C")
        (span (@ (class "white white-square")) "\u265B")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "blank white-square")) "&nbsp;")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "white white-square")) "\u265C")
        (span (@ (class "blank black-square")) "&nbsp;"))
       (div
        (span (@ (class "border")) "1")
        (a ((class "black black-square")) "\u265F")
        (span (@ (class "black white-square")) "\u265C")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "black white-square")) "\u265D")
        (span (@ (class "blank black-square")) "&nbsp;")
        (span (@ (class "white white-square")) "\u265E")
        (span (@ (class "black black-square")) "\u265D")
        (span (@ (class "white white-square")) "\u265A"))
       (span (@ (class "border")) "&nbsp;")
       (span (@ (class "border")) "a")
       (span (@ (class "border")) "b")
       (span (@ (class "border")) "c")
       (span (@ (class "border")) "d")
       (span (@ (class "border")) "e")
       (span (@ (class "border")) "f")
       (span (@ (class "border")) "g")
       (span (@ (class "border")) "h")))
